// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const browserStorage = typeof window !== 'undefined' && typeof window.sessionStorage !== 'undefined'
  ? window.sessionStorage
  : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: browserStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'implicit',
  },
  // Add error handling for auth errors
  global: {
    headers: {
      'X-Client-Info': 'paystore-pos/1.0.0',
    },
  },
  db: {
    schema: 'public',
  },
});

// Global debug wrapper for all Supabase function invocations.
try {
  const originalInvoke = (supabase.functions as any).invoke.bind(supabase.functions);
  (supabase.functions as any).invoke = async (name: string, opts: any) => {
    try {
      const sanitizedHeaders = { ...(opts?.headers || {}) };
      delete sanitizedHeaders.Authorization;
      delete sanitizedHeaders.authorization;
      console.debug('[supabase.functions.invoke] name=', name, 'body=', opts?.body, 'headers=', sanitizedHeaders);
    } catch (err) {
      console.warn('[supabase.functions.invoke] debug log failed', err);
    }
    return originalInvoke(name, opts);
  };
} catch (err) {
  console.warn('[supabase.functions.invoke] wrapper setup failed', err);
}