project_id = "pdjroppybrndaldgcdzk"

[functions.delete-owner]
verify_jwt = false

[functions.approve-owner]
verify_jwt = false

[functions.secure-store-login]
verify_jwt = false

[functions.staff-login]
verify_jwt = false

[functions.create-staff]
verify_jwt = false

[functions.delete-staff]
verify_jwt = false

[functions.get-store-staff]
verify_jwt = false

[functions.create-owner]
verify_jwt = false

[functions.verify-face]
verify_jwt = false

[functions.online-order-webhook]
verify_jwt = false

[functions.sync-orders]
verify_jwt = false

[functions.sync-store-data]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.create-store]
verify_jwt = false